environments:
  - name: prod
    variables:
      GF_SECURITY_ADMIN_USER: admin  # Use secrets for sensitive data
      GF_SECURITY_ADMIN_PASSWORD: admin123  # Use secrets for sensitive data

components:
  - name: weatherview
    image: grafana/grafana:latest
    ports:
      - name: web
        port: 3000
    public: true
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    secrets:
      - GF_SECURITY_ADMIN_PASSWORD
